import React from 'react'
import Head from 'next/head'
import {Footer,Navbar} from "./index";
const Layout = ({children}) => {
    return(
        <div className={'font-pop'}>
            <Head>
                <title>React</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,200;1,300;1,400;1,500;1,600&display=swap" rel="stylesheet"/>
            </Head>
            <header>
                <Navbar/>
            </header>
            <main>{children}</main>
            <footer className='font-pop bg-gray-700'>
                <Footer/>
            </footer>
        </div>
    )
}
export default Layout