import React from 'react'
import Head from 'next/head'
import { Footer, Navbar } from "./index";
import { useRouter } from 'next/router';

const Layout = ({ children }) => {
    const router = useRouter();
    const {pathname} = router;
    const isLogIn = pathname === '/login';
    const isSignIn = pathname === '/signin';
    if (isLogIn || isSignIn) {
        return (
            <div className='font-pop'>
                <Head>
                    <title>React-Ecommerce</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <link rel="preconnect" href="https://fonts.googleapis.com" />
                    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,200;1,300;1,400;1,500;1,600&display=swap" rel="stylesheet" />
                </Head>
                <main>{children}</main>
            </div>
        )
    }

    return (
        <div className='font-pop'>
            <Head>
                <title>React-Ecommerce</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,200;1,300;1,400;1,500;1,600&display=swap" rel="stylesheet" />
            </Head>
            <Navbar />
            <main>{children}</main>
            <Footer />
        </div>
    )
}
export default Layout